name: signum_chat
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.3
  cupertino_icons: ^1.0.8
  intl:
  firebase_core: ^3.12.1
  firebase_auth:
  cloud_firestore:
  firebase_database: ^11.3.4
  equatable: ^2.0.7
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  record: ^5.2.1
  path_provider: ^2.1.5
  audio_waveforms: ^1.3.0
  firebase_storage: ^12.4.4
  flutter_cache_manager: ^3.4.1
  flutter_webrtc: ^0.12.12+hotfix.1
  universal_html: ^2.2.4
  file_picker: ^9.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/chat_background.png
